name: build process
run-name: Build process

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:

  build-extension:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container: 
      image: ghcr.io/gbraad-actions/fedora:stable
      options: --privileged

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install project dependencies
        run: |
          npm install

      - name: Upload kclient
        uses: actions/upload-artifact@v4
        with:
          name: kclient
          path: .
          retention-days: 7
